name: Deploy to GitHub pages
'on':
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: git config --global user.name ${{ secrets.REACT_APP_USERNAME }}
      - run: git config --global user.email ${{ secrets.REACT_APP_EMAIL }}
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."